using System.Runtime.InteropServices;
using System.ComponentModel;
using System.Text;
namespace MicOnly;
static class DriverBranding
{
 [StructLayout(LayoutKind.Sequential)]struct DevInfo{public uint size;public Guid classGuid;public uint devInst;public nint reserved;}
 [DllImport("setupapi.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern nint SetupDiGetClassDevs(nint classGuid,string? enumerator,nint parent,uint flags);
 [DllImport("setupapi.dll",SetLastError=true)]static extern bool SetupDiEnumDeviceInfo(nint set,uint index,ref DevInfo info);
 [DllImport("setupapi.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool SetupDiGetDeviceRegistryProperty(nint set,ref DevInfo info,uint property,out uint type,byte[] buffer,uint length,out uint required);
 [DllImport("setupapi.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool SetupDiSetDeviceRegistryProperty(nint set,ref DevInfo info,uint property,byte[] buffer,uint length);
 [DllImport("setupapi.dll")]static extern bool SetupDiDestroyDeviceInfoList(nint set);
 [StructLayout(LayoutKind.Sequential)]struct PropertyKey{public Guid format;public uint id;}
 [DllImport("setupapi.dll",EntryPoint="SetupDiGetClassDevsW",CharSet=CharSet.Unicode,SetLastError=true)]static extern nint InterfaceSet(ref Guid classGuid,string? enumerator,nint parent,uint flags);
 [DllImport("setupapi.dll",SetLastError=true)]static extern bool SetupDiEnumDeviceInterfaces(nint set,nint device,ref Guid guid,uint index,ref DevInfo data);
 [DllImport("setupapi.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool SetupDiGetDeviceInterfaceDetail(nint set,ref DevInfo data,nint detail,uint length,out uint required,ref DevInfo device);
 [DllImport("setupapi.dll",EntryPoint="SetupDiSetDeviceInterfacePropertyW",SetLastError=true)]static extern bool SetInterfaceProperty(nint set,ref DevInfo data,ref PropertyKey key,uint type,byte[] value,uint length,uint flags);
 static object RenameInterfaces(){var results=new List<object>();foreach(var text in new[]{"6994ad04-93ef-11d0-a3cc-00a0c9223196","65e8773d-8f56-11d0-a3b9-00a0c9223196","65e8773e-8f56-11d0-a3b9-00a0c9223196"}){var guid=new Guid(text);var set=InterfaceSet(ref guid,null,0,18);if(set==-1)continue;try{for(uint i=0;;i++){var data=new DevInfo{size=(uint)Marshal.SizeOf<DevInfo>()};if(!SetupDiEnumDeviceInterfaces(set,0,ref guid,i,ref data))break;var device=new DevInfo{size=(uint)Marshal.SizeOf<DevInfo>()};SetupDiGetDeviceInterfaceDetail(set,ref data,0,0,out var required,ref device);var detail=Marshal.AllocHGlobal((int)required);try{Marshal.WriteInt32(detail,8);if(!SetupDiGetDeviceInterfaceDetail(set,ref data,detail,required,out _,ref device))continue;var hardware=new byte[8192];if(!SetupDiGetDeviceRegistryProperty(set,ref device,1,out _,hardware,(uint)hardware.Length,out _)||!Encoding.Unicode.GetString(hardware).Split('\0').Contains(@"ROOT\VEN_SSGG&DEV_0001",StringComparer.OrdinalIgnoreCase))continue;var key=new PropertyKey{format=new Guid("026e516e-b814-414b-83cd-856d6fef4822"),id=2};var value=Encoding.Unicode.GetBytes("YappGG Audio\0");bool ok=SetInterfaceProperty(set,ref data,ref key,18,value,(uint)value.Length,0);results.Add(new{interfaceClass=text,renamed=ok,error=ok?0:Marshal.GetLastWin32Error()});}finally{Marshal.FreeHGlobal(detail);}}}finally{SetupDiDestroyDeviceInfoList(set);}}return results;}
 public static object Rename(){var set=SetupDiGetClassDevs(0,null,0,6);if(set==-1)throw new Win32Exception(Marshal.GetLastWin32Error());try{for(uint index=0;;index++){var info=new DevInfo{size=(uint)Marshal.SizeOf<DevInfo>()};if(!SetupDiEnumDeviceInfo(set,index,ref info))break;var hardware=new byte[8192];if(!SetupDiGetDeviceRegistryProperty(set,ref info,1,out _,hardware,(uint)hardware.Length,out _)||!Encoding.Unicode.GetString(hardware).Split('\0').Contains(@"ROOT\VEN_SSGG&DEV_0001",StringComparer.OrdinalIgnoreCase))continue;var name=Encoding.Unicode.GetBytes("YappGG Audio\0");if(!SetupDiSetDeviceRegistryProperty(set,ref info,12,name,(uint)name.Length))throw new Win32Exception(Marshal.GetLastWin32Error());return new{renamed=true,name="YappGG Audio",interfaces=RenameInterfaces()};}throw new InvalidOperationException("Microphone driver is not installed.");}finally{SetupDiDestroyDeviceInfoList(set);}}
}
