const fs=require('fs'),path=require('path');
// A user-facing inbox is separate from the managed WAV/video library.
class ImportInbox{
 constructor({directory,importFiles,onChange}){this.directory=directory;this.importFiles=importFiles;this.onChange=onChange;fs.mkdirSync(directory,{recursive:true});this.index=path.join(directory,'.imported.json');try{this.known=JSON.parse(fs.readFileSync(this.index,'utf8'));}catch{this.known={};}this.pending=false;this.closed=false;}
 async files(directory=this.directory,depth=0){if(depth>8)throw Error("Keep import folder nesting within eight levels.");const files=[];for(const item of await fs.promises.readdir(directory,{withFileTypes:true})){if(item.name.startsWith('.')||item.isSymbolicLink())continue;const file=path.join(directory,item.name);if(item.isDirectory())files.push(...await this.files(file,depth+1));else if(item.isFile())files.push(file);}return files;}
 async scan(){if(this.closed)return;if(this.running){this.pending=true;return this.running;}this.running=(async()=>{const files=await this.files();const changed=[];for(const file of files){if(!require('./soundboard-library.cjs').supported.has(path.extname(file).toLowerCase())&&path.extname(file).toLowerCase()!=='.zip')continue;const stat=await fs.promises.stat(file);const fingerprint=stat.size+':'+stat.mtimeMs;if(this.known[file]!==fingerprint)changed.push({file,fingerprint});}if(!changed.length)return;await new Promise(resolve=>setTimeout(resolve,800));for(const item of changed){const stat=await fs.promises.stat(item.file).catch(()=>null);if(!stat||item.fingerprint!==stat.size+':'+stat.mtimeMs){this.pending=true;continue;}const result=await this.importFiles([item.file],path.relative(this.directory,path.dirname(item.file)).split(path.sep).join('/'));this.known[item.file]=item.fingerprint;await fs.promises.writeFile(this.index,JSON.stringify(this.known));this.onChange(result);}})().finally(()=>{this.running=null;if(this.pending&&!this.closed){this.pending=false;this.schedule();}});return this.running;}
 schedule(){clearTimeout(this.timer);this.timer=setTimeout(()=>this.scan().catch(error=>this.onChange({error:error.message})),1000);}
 start(){this.watcher=fs.watch(this.directory,{recursive:true},(_,name)=>{if(name&&!String(name).startsWith('.'))this.schedule();});this.interval=setInterval(()=>this.schedule(),15000);this.schedule();}
 close(){this.closed=true;clearTimeout(this.timer);clearInterval(this.interval);this.watcher?.close();}
}
module.exports={ImportInbox};
