const path=require('path'),{wheelFolders,visibleFolder}=require('./wheel-folders.cjs');
class SoundWheel{
 constructor({BrowserWindow,screen,directory,list,folders,play,folder,shortcut,onError,saveFolder,layout,globalShortcut,page,savePage,favorites,toggleFavorite,pointer}){Object.assign(this,{BrowserWindow,screen,directory,list,folders,play,folder,shortcut,onError,saveFolder,layout,globalShortcut,page,savePage,favorites,toggleFavorite,pointer});this.generation=0;}
 async prepare(){if(!this.window||this.window.isDestroyed()){
  const win=this.window=new this.BrowserWindow({width:560,height:600,show:false,frame:false,transparent:true,resizable:false,focusable:true,alwaysOnTop:true,skipTaskbar:true,hasShadow:false,title:'YappGG sound wheel',webPreferences:{preload:path.join(this.directory,'../host/wheel-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});
  win.setAlwaysOnTop(true,'pop-up-menu');win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',event=>event.preventDefault());win.on('close',event=>{if(!this.disposed){event.preventDefault();this.close();}});win.on('blur',()=>{if(win.isVisible())this.close();});win.on('closed',()=>{if(this.window===win)this.window=null;});this.ready=win.loadFile(path.join(this.directory,'wheel.html'));
 }return this.ready;
 }
 async open(){if(this.window?.isVisible()){this.close();return;}const generation=++this.generation;await this.prepare();if(this.disposed||generation!==this.generation)return;const cursor=this.screen.getCursorScreenPoint(),area=this.screen.getDisplayNearestPoint(cursor).workArea;const settings=this.layout?.()||{size:560,slots:8};const width=Math.min(settings.size,area.width),height=Math.min(settings.size+40,area.height);const x=Math.round(Math.max(area.x,Math.min(area.x+area.width-width,area.x+area.width/2-width/2))),y=Math.round(Math.max(area.y,Math.min(area.y+area.height-height,area.y+area.height/2-height/2)));
 this.window.setBounds({x,y,width,height});const roots=wheelFolders(this.folders()),folder=visibleFolder(this.folder(),roots);this.window.webContents.send('wheel:open',{page:this.page?.(folder)||0,favorites:this.favorites?.()||[],slots:settings.slots,sounds:this.list(),folders:roots,folder,shortcut:this.shortcut(),initialCursor:{x:width/2,y:height/2}});this.window.show();this.window.focus();this.pointer?.({x:Math.round(x+width/2),y:Math.round(y+height/2)});if(this.globalShortcut&&!this.globalShortcut.isRegistered('Escape'))this.escapeRegistered=this.globalShortcut.register('Escape',()=>this.close());
 }
 close(){++this.generation;if(this.escapeRegistered){this.globalShortcut.unregister('Escape');this.escapeRegistered=false;}this.window?.hide();}
 async choose(id){if(!this.window?.isVisible())throw Error('Open the sound wheel first.');const exists=this.list().some(s=>s.id===id);if(!exists)throw Error('This sound was removed.');const generation=this.generation;try{const result=await this.play(id);if(generation===this.generation)this.close();return result;}catch(error){this.onError(error);throw error;}}
 command(event,command,id){if(event.sender!==this.window?.webContents)throw Error('Invalid sound wheel window.');if(command==='cancel'){this.close();return true;}if(command==='folder'){if(!['All',...this.folders()].includes(id))throw Error('Choose a sound folder.');this.saveFolder(id);return {folder:id,page:this.page?.(id)||0};}if(command==='page'){if(!id||!['All',...this.folders()].includes(id.folder)||!Number.isInteger(id.page)||id.page<0)throw Error('Invalid wheel page.');return this.savePage(id.folder,id.page);}if(command==='favorite'){if(!id||!this.folders().includes(id.folder))throw Error('Invalid favorite folder.');return this.toggleFavorite(id.folder);}if(command==='play')return this.choose(id);throw Error('Unknown wheel action.');}
 dispose(){if(this.escapeRegistered){this.globalShortcut.unregister('Escape');this.escapeRegistered=false;}this.disposed=true;++this.generation;clearTimeout(this.releaseTimer);this.window?.destroy();this.window=null;}
}
module.exports={SoundWheel};
