<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><PlatformTarget>x64</PlatformTarget><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Reference Include="Interop.SonarAPOSettingsControl"><HintPath>../../native-runtime/Interop.SonarAPOSettingsControl.dll</HintPath></Reference></ItemGroup></Project>
