window.createSoundboardComponents=(O,Icon)=>{
 const R=O.React,el=R.createElement;
 const errorText=error=>String(error?.message||error).replace(/^Error invoking remote method '[^']+': (?:Error: )?/,'');
 const SoundCard=R.memo(function SoundCard({sound,playing,update,play,remove,stop}){
  const [volume,setVolume]=R.useState(sound.volume),[shortcut,setShortcut]=R.useState(sound.shortcut),timer=R.useRef();
  R.useEffect(()=>setShortcut(sound.shortcut),[sound.shortcut]);
  const volumeChange=value=>{setVolume(value);clearTimeout(timer.current);timer.current=setTimeout(()=>update(sound.id,{volume:value}),100);};
  return el('article',{className:'sound-card'+(playing?' is-playing':'')},
   el('button',{className:'sound-play','aria-label':(playing?'Replay ':'Play ')+sound.name,onClick:()=>play(sound.id),title:'Play through your microphone'},el('span',{'aria-hidden':true},playing?'↻':'▶')),
   el('div',{className:'sound-details'},el('input',{className:'sound-name','aria-label':'Sound name',title:'Click to rename '+sound.name,defaultValue:sound.name,maxLength:100,onBlur:event=>{if(event.target.value.trim()!==sound.name)update(sound.id,{name:event.target.value});}}),el('span',{className:'sound-duration'},String(Math.floor(sound.durationSeconds/60)).padStart(2,'0')+':'+String(Math.floor(sound.durationSeconds%60)).padStart(2,'0')+(playing?' · Playing':''))),
   el('label',{className:'sound-volume'},'Volume '+Math.round(volume*100)+'%',el('input',{type:'range',min:0,max:100,value:Math.round(volume*100),'aria-label':'Volume for '+sound.name,onChange:event=>volumeChange(Number(event.target.value)/100)})),
   el('label',{className:'sound-shortcut'},'Shortcut',el('input',{readOnly:true,value:shortcut?shortcut.replace(/Control/g,'Ctrl').replace(/\+/g,' + '):'Set shortcut','aria-label':'Keybind for '+sound.name,title:'Press a modifier and a key. Backspace removes the binding.',onKeyDown:async event=>{if(['Tab','Escape'].includes(event.key))return;event.preventDefault();const modifiers=[];if(event.ctrlKey)modifiers.push('Control');if(event.altKey)modifiers.push('Alt');if(event.shiftKey)modifiers.push('Shift');if(event.metaKey)modifiers.push('Super');const key=event.key.toUpperCase();if(event.key!=='Backspace'&&(!modifiers.length||!/^([A-Z0-9]|F([1-9]|1[0-9]|2[0-4]))$/.test(key)))return;const previous=shortcut,next=event.key==='Backspace'?'':modifiers.concat(key).join('+');setShortcut(next);if(!await update(sound.id,{shortcut:next}))setShortcut(previous);}})),
   el('div',{className:'sound-actions'},el('button',{onClick:()=>stop(sound.id),'aria-label':'Stop '+sound.name,title:'Stop sound'},el(Icon,{name:'stop',size:14})),el('button',{onClick:()=>remove(sound.id),'aria-label':'Remove '+sound.name,title:'Remove sound'},el(Icon,{name:'trash',size:15}))));
 });
 function Soundboard({close}){
  const [sounds,setSounds]=R.useState([]),[playing,setPlaying]=R.useState([]),[message,setMessage]=R.useState(''),[importing,setImporting]=R.useState(false),[query,setQuery]=R.useState(''),[mic,setMic]=R.useState({running:!!window.__audioStatus?.running,muted:!!window.__audioStatus?.muted});
  R.useEffect(()=>{let live=true;micHost.soundboard('list').then(rows=>{if(live)setSounds(rows);}).catch(error=>setMessage(errorText(error)));const listener=event=>{const ids=event.detail.soundboardPlaying||[];setMic(previous=>previous.running===!!event.detail.running&&previous.muted===!!event.detail.muted?previous:{running:!!event.detail.running,muted:!!event.detail.muted});setPlaying(previous=>previous.join(',')===ids.join(',')?previous:ids);};window.addEventListener('mic-audio-status',listener);return()=>{live=false;window.removeEventListener('mic-audio-status',listener);};},[]);
  const update=R.useCallback(async(id,values)=>{try{const rows=await micHost.soundboard('update',{id,...values});setSounds(rows);setMessage('');return true;}catch(error){setMessage(errorText(error));return false;}},[]);
  const play=R.useCallback(async id=>{try{setPlaying(previous=>previous.includes(id)?previous:[...previous,id]);await micHost.soundboard('play',{id});setMessage('');}catch(error){setPlaying(previous=>previous.filter(value=>value!==id));setMessage(errorText(error));}},[]);
  const remove=R.useCallback(async id=>{try{setSounds(await micHost.soundboard('remove',{id}));}catch(error){setMessage(errorText(error));}},[]);
  const stop=R.useCallback(async id=>{try{await micHost.soundboard('stop',id?{id}:{});setPlaying(previous=>id?previous.filter(value=>value!==id):[]);}catch(error){setMessage(errorText(error));}},[]);
  const importSounds=async()=>{setImporting(true);setMessage('Importing sounds… You can keep using your mic.');try{const result=await micHost.soundboard('import');setSounds(result.sounds);setMessage(result.imported+' sounds imported.'+(result.skipped.length?' '+result.skipped.length+' skipped: '+result.skipped.slice(0,5).map(s=>s.name+' ('+s.reason+')').join('; '):''));}catch(error){setMessage(errorText(error));}finally{setImporting(false);}};
  return el('div',{className:'settings-backdrop soundboard-backdrop'},el('section',{className:'settings-panel soundboard-panel',role:'dialog','aria-modal':true,'aria-label':'Soundboard'},
   el('div',{className:'settings-heading'},el('div',null,el('div',{className:'soundboard-eyebrow'},'YAPPGG / SOUNDS'),el('h2',null,'Soundboard')),el('div',{className:'soundboard-header-actions'},el('span',{className:'soundboard-mic-status'+(mic.running&&!mic.muted?' ready':'')},el('span',{'aria-hidden':true}),mic.muted?'Mic muted':mic.running?'Mic ready':'Mic stopped'),el('button',{'aria-label':'Close soundboard',onClick:close},el(Icon,{name:'close'})))),
   el('p',{className:'soundboard-description'},'Your clips, ready for your next call.'),
   el('div',{className:'soundboard-toolbar'},el('button',{className:'soundboard-import',onClick:importSounds,disabled:importing},el(Icon,{name:'upload',size:16}),importing?'Importing…':'Import audio / ZIP'),el('button',{onClick:()=>stop()},el(Icon,{name:'stop',size:13}),'Stop all'),el('input',{type:'search',placeholder:'Search sounds','aria-label':'Search sounds',value:query,onChange:event=>setQuery(event.target.value)})),
   el('div',{className:'soundboard-library-meta'},el('span',null,sounds.length+' '+(sounds.length===1?'sound':'sounds')),el('span',null,playing.length?playing.length+' playing':'Shortcuts work in the tray')),message&&el('p',{className:'soundboard-status',role:'status'},message),!sounds.length&&el('div',{className:'soundboard-empty'},el(Icon,{name:'volume',size:36}),el('h3',null,'Add your first sounds'),el('p',null,'Import a collection into your library with audio, video or a ZIP pack. Then choose a shortcut for each clip.')),
   el('div',{className:'soundboard-grid'},sounds.filter(sound=>sound.name.toLowerCase().includes(query.toLowerCase())).map(sound=>el(SoundCard,{key:sound.id,sound,playing:playing.includes(sound.id),update,play,remove,stop})))));
 }
 const SoundboardLauncher=R.memo(function SoundboardLauncher(){const [open,setOpen]=R.useState(false);R.useEffect(()=>{const listener=event=>{if(event.key==='Escape')setOpen(false);};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);return el(R.Fragment,null,el('button',{className:'quiet-button','aria-label':'Open soundboard',onClick:()=>setOpen(true)},'Soundboard'),open&&el(Soundboard,{close:()=>setOpen(false)}));});
 return {SoundboardLauncher};
};

