(()=>{
 const $=id=>document.getElementById(id),svg=$('segments'),dial=$('dial'),ns='http://www.w3.org/2000/svg';let sounds=[],visible=[],page=0,selected=-1,submitting=false,trigger='q',initial=null,moved=false;
 const point=(angle,r)=>[260+Math.cos(angle)*r,260+Math.sin(angle)*r];
 function node(tag,attrs,text){const n=document.createElementNS(ns,tag);for(const [key,value] of Object.entries(attrs))n.setAttribute(key,value);if(text!==undefined)n.textContent=text;return n;}
 function filtered(){return sounds.filter(s=>$('folder').value==='All'||(s.folder||'Sounds')===$('folder').value);}
 function selection(index){selected=index;for(const [i,path] of [...svg.querySelectorAll('.slice')].entries()){path.classList.toggle('active',i===index);path.setAttribute('aria-pressed',i===index?'true':'false');}const sound=visible[index];$('selected-name').textContent=sound?sound.name:sounds.length?'Choose a sound':'No sounds yet';$('hub-help').textContent=sound?'Release to play':'Drag outward';document.querySelector('.hub').classList.toggle('selected',!!sound);}
 function render(){const filteredSounds=filtered();const pages=Math.max(1,Math.ceil(filteredSounds.length/8));page=Math.max(0,Math.min(pages-1,page));visible=filteredSounds.slice(page*8,page*8+8);svg.replaceChildren();for(let i=0;i<8;i++){const middle=-Math.PI/2+i*Math.PI/4,a=middle-Math.PI/8+.017,b=middle+Math.PI/8-.017,[ax,ay]=point(a,238),[bx,by]=point(b,238),[cx,cy]=point(b,92),[dx,dy]=point(a,92),sound=visible[i];const path=node('path',{d:`M ${ax} ${ay} A 238 238 0 0 1 ${bx} ${by} L ${cx} ${cy} A 92 92 0 0 0 ${dx} ${dy} Z`,class:'slice'+(sound?'':' disabled'),role:'button',tabindex:sound?'0':'-1','aria-label':sound?'Play '+sound.name:'Empty wheel slot','data-index':i});path.addEventListener('keydown',event=>{if(sound&&['Enter',' '].includes(event.key)){event.preventDefault();selection(i);choose();}});svg.append(path);if(sound){const [x,y]=point(middle,167);let label=sound.name;const words=label.match(/.{1,14}(?:\s|$)|.{1,14}/g)||[label];const text=node('text',{x,y:y-6});words.slice(0,2).forEach((word,line)=>text.append(node('tspan',{x,dy:line?17:0},word.trim()+(line===1&&words.length>2?'…':''))));svg.append(text);svg.append(node('text',{x,y:y+32,class:'number'},String(page*8+i+1).padStart(2,'0')));}}selection(-1);$('page').textContent=`${page+1} / ${pages} · ${filteredSounds.length} sounds`;$('previous').disabled=page===0;$('next').disabled=page===pages-1;$('empty').hidden=!!sounds.length;}
 function locate(event){const matrix=svg.getScreenCTM();if(!matrix)return;const point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const local=point.matrixTransform(matrix.inverse()),dx=local.x-260,dy=local.y-260;if(initial&&Math.hypot(event.clientX-initial.x,event.clientY-initial.y)>12)moved=true;const radius=Math.hypot(dx,dy);if(radius<92||radius>280)return selection(-1);const angle=(Math.atan2(dy,dx)+Math.PI/2+Math.PI*2)%(Math.PI*2);const index=Math.floor((angle+Math.PI/8)/(Math.PI/4))%8;selection(visible[index]?index:-1);}
 async function choose(){const sound=visible[selected];if(!sound||submitting)return;submitting=true;try{await wheelHost.play(sound.id);}catch(error){$('help').textContent=String(error.message||error);submitting=false;}}
 dial.addEventListener('pointermove',locate);dial.addEventListener('pointerdown',event=>{if(event.button!==0)return;event.preventDefault();initial={x:event.clientX,y:event.clientY};moved=false;locate(event);dial.setPointerCapture(event.pointerId);});dial.addEventListener('pointerup',event=>{if(event.button!==0)return;locate(event);if(selected>=0)choose();});
 document.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();wheelHost.cancel();}if(event.target.tagName==='SELECT')return;if(event.key==='ArrowRight')next(1);if(event.key==='ArrowLeft')next(-1);});document.addEventListener('keyup',event=>{if(event.target.tagName==='SELECT')return;if(event.key.toLowerCase()===trigger&&moved&&selected>=0)choose();});
 function next(delta){page+=delta;render();}let scrolledAt=0;dial.addEventListener('wheel',event=>{event.preventDefault();if(Date.now()-scrolledAt<180||event.deltaY===0)return;scrolledAt=Date.now();next(event.deltaY>0?1:-1);},{passive:false});$('previous').onclick=()=>next(-1);$('next').onclick=()=>next(1);$('folder').onchange=()=>{page=0;render();};$('cancel').onclick=()=>wheelHost.cancel();
 wheelHost.onOpen(data=>{sounds=data.sounds;page=0;submitting=false;initial=data.initialCursor;moved=false;trigger=(data.shortcut?.split('+').pop()||'q').toLowerCase();$('folder').replaceChildren(...['All',...data.folders].map(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;return option;}));$('folder').value=data.folder&&[...$('folder').options].some(o=>o.value===data.folder)?data.folder:'All';$('help').textContent='Drag toward a sound and release to play · Esc cancels';render();});
})();
