(()=>{
 const $=id=>document.getElementById(id),svg=$('segments'),dial=$('dial'),ns='http://www.w3.org/2000/svg';let sounds=[],visible=[],page=0,selected=-1,submitting=false,trigger='q',initial=null,moved=false,slots=8;
 const point=(angle,r)=>[260+Math.cos(angle)*r,260+Math.sin(angle)*r];
 function click(button,action){button.addEventListener('pointerup',event=>{if(event.button!==0||button.disabled)return;event.preventDefault();event.stopPropagation();action();});button.addEventListener('click',event=>{if(event.detail===0&&!button.disabled){event.preventDefault();action();}});}
 function node(tag,attrs,text){const n=document.createElementNS(ns,tag);for(const [key,value] of Object.entries(attrs))n.setAttribute(key,value);if(text!==undefined)n.textContent=text;return n;}
 function filtered(){const folder=$('folder').value;return folder==='All'?sounds:sounds.filter(s=>(s.folder||'Sounds')===folder||(s.folder||'Sounds').startsWith(folder+'/'));}
 function pagesForView(){const items=filtered();if($('folder').value!=='All')return Array.from({length:Math.max(1,Math.ceil(items.length/slots))},(_,i)=>({items:items.slice(i*slots,i*slots+slots),folder:$('folder').value}));const groups=new Map();for(const sound of items){const folder=sound.folder||'Sounds';if(!groups.has(folder))groups.set(folder,[]);groups.get(folder).push(sound);}const pages=[];for(const [folder,group] of [...groups].sort(([a],[b])=>a.localeCompare(b)))for(let i=0;i<group.length;i+=slots)pages.push({items:group.slice(i,i+slots),folder});return pages.length?pages:[{items:[],folder:'All'}];}
 const measuring=document.createElement('canvas').getContext('2d');measuring.font='500 11px Inter';
 function labelLines(name,width){const chars=Array.from(name.trim()),lines=[];for(let line=0;line<2&&chars.length;line++){let text='';while(chars.length&&measuring.measureText(text+chars[0]).width<=width)text+=chars.shift();if(line===1&&chars.length){while(text&&measuring.measureText(text+'…').width>width)text=text.slice(0,-1);text+='…';}lines.push(text.trim());}return lines.length?lines:['Sound'];}
 function selection(index){selected=index;for(const [i,path] of [...svg.querySelectorAll('.slice')].entries()){path.classList.toggle('active',i===index);path.setAttribute('aria-pressed',i===index?'true':'false');}const sound=visible[index];$('selected-name').textContent=sound?sound.name:sounds.length?'Choose a sound':'No sounds yet';$('hub-help').textContent=sound?'Release to play':pagesForView().length>1?'Click Next for more':'Drag to play';document.querySelector('.hub').classList.toggle('selected',!!sound);}
 function siblingFolders(){const current=$('folder').value,parent=current.includes('/')?current.slice(0,current.lastIndexOf('/')):'';return [...$('folder').options].map(o=>o.value).filter(f=>parent?f.startsWith(parent+'/')&&!f.slice(parent.length+1).includes('/'):!f.includes('/'));}
 function render(){const groups=pagesForView(),pages=groups.length;page=Math.max(0,Math.min(pages-1,page));visible=groups[page].items;svg.replaceChildren(node('circle',{cx:260,cy:260,r:190,class:'ring'}));for(let i=0;i<slots;i++){const middle=-Math.PI/2+i*Math.PI*2/slots,sound=visible[i],[x,y]=point(middle,190);const half=Math.min(64,Math.floor(190*Math.sin(Math.PI/slots)*.82));const tile=node('path',{d:`M ${x-half+7} ${y-30} h ${half*2-14} q 7 0 7 7 v 46 q 0 7 -7 7 h -${half*2-14} q -7 0 -7 -7 v -46 q 0 -7 7 -7 Z`,class:'slice'+(sound?'':' disabled'),role:'button',tabindex:sound?'0':'-1','aria-label':sound?'Play '+sound.name:'Empty wheel slot','data-index':i});tile.addEventListener('keydown',event=>{if(sound&&['Enter',' '].includes(event.key)){event.preventDefault();selection(i);choose();}});if(sound)tile.append(node('title',{},sound.name));svg.append(tile);if(sound){const label=node('text',{x,y,class:'sound-label'}),lines=labelLines((sound.isFolder?'▸ ':'')+sound.name,half*2-16);lines.forEach((line,index)=>label.append(node('tspan',{x,y:y+(lines.length>1?-3:4)+index*13},line)));svg.append(label);}}selection(-1);$('folder-picker').textContent=$('folder').value.replaceAll('/',' / ')+' ▾';$('page').textContent=`${page+1} / ${pages}`;document.querySelector('nav').hidden=pages<=1;$('previous').disabled=page===0;$('next').disabled=page===pages-1;$('empty').hidden=!!filtered().length;$('up').hidden=$('folder').value==='All';const peers=siblingFolders(),index=peers.indexOf($('folder').value);$('folder-previous').disabled=index<=0;$('folder-next').disabled=index>=peers.length-1;$('group').hidden=$('folder').value!=='All';$('group').textContent=groups[page].folder.replaceAll('/',' / ');}
 function locate(event){const matrix=svg.getScreenCTM();if(!matrix)return;const point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const local=point.matrixTransform(matrix.inverse()),dx=local.x-260,dy=local.y-260;if(initial&&Math.hypot(event.clientX-initial.x,event.clientY-initial.y)>12)moved=true;const radius=Math.hypot(dx,dy);if(radius<92||radius>280)return selection(-1);const angle=(Math.atan2(dy,dx)+Math.PI/2+Math.PI*2)%(Math.PI*2);const index=Math.floor((angle+Math.PI/slots)/(Math.PI*2/slots))%slots;selection(visible[index]?index:-1);}
 async function choose(){const sound=visible[selected];if(!sound||submitting)return;submitting=true;try{await wheelHost.play(sound.id);}catch(error){$('help').textContent=String(error.message||error);submitting=false;}}
 document.addEventListener('pointermove',event=>{if(!$('folder-menu').hidden||event.target.closest('button,select'))selection(-1);else locate(event);});dial.addEventListener('pointerdown',event=>{if(event.button!==0)return;event.preventDefault();initial={x:event.clientX,y:event.clientY};moved=false;locate(event);});document.addEventListener('pointerup',event=>{if(!$('folder-menu').hidden&&!event.target.closest('.filter')){hideFolders();event.preventDefault();return;}if(event.button!==0||event.target.closest('button,select'))return;locate(event);if(selected>=0)choose();});
 document.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();wheelHost.cancel();}if(event.target.tagName==='SELECT')return;});document.addEventListener('keyup',event=>{if(event.target.tagName==='SELECT')return;if(event.key.toLowerCase()===trigger&&moved&&selected>=0)choose();});
 function next(delta){page+=delta;render();}dial.addEventListener('wheel',event=>event.preventDefault(),{passive:false});click($('previous'),()=>next(-1));click($('next'),()=>next(1));function hideFolders(){$('folder-menu').hidden=true;$('folder-picker').setAttribute('aria-expanded','false');}click($('folder-picker'),()=>{const open=$('folder-menu').hidden;$('folder-menu').hidden=!open;$('folder-picker').setAttribute('aria-expanded',String(open));selection(-1);});async function selectFolder(folder){hideFolders();$('folder').value=folder;page=0;render();try{await wheelHost.folder(folder);}catch(error){$('hub-help').textContent=String(error.message||error);}}function changeFolder(delta){const peers=siblingFolders(),index=Math.max(0,Math.min(peers.length-1,peers.indexOf($('folder').value)+delta));selectFolder(peers[index]);}click($('folder-previous'),()=>changeFolder(-1));click($('folder-next'),()=>changeFolder(1));$('folder').onchange=()=>selectFolder($('folder').value);click($('up'),()=>{const folder=$('folder').value;selectFolder(folder.includes('/')?folder.slice(0,folder.lastIndexOf('/')):'All');});click($('cancel'),()=>wheelHost.cancel());
 wheelHost.onOpen(data=>{hideFolders();slots=[4,6,8,10,12].includes(data.slots)?data.slots:8;sounds=data.sounds;page=0;submitting=false;initial=data.initialCursor;moved=false;trigger=(data.shortcut?.split('+').pop()||'q').toLowerCase();$('folder').replaceChildren(...['All',...data.folders].map(name=>{const option=document.createElement('option');option.value=name;option.textContent=name.replaceAll('/',' / ');return option;}));$('folder-menu').replaceChildren(...['All',...data.folders].map(name=>{const button=document.createElement('button');button.type='button';button.textContent=name.replaceAll('/',' / ');button.setAttribute('role','option');button.dataset.folder=name;click(button,()=>selectFolder(name));return button;}));$('folder').value=data.folder&&[...$('folder').options].some(o=>o.value===data.folder)?data.folder:'All';$('help').textContent='Drag toward a sound and release to play · Esc cancels';render();});
})();
